AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HighlightAI - Authentication and Video Upload Module

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256

Resources:
  # S3 BUCKET FOR RAW VIDEO UPLOADS
    # S3 BUCKET FOR LAMBDA LAYERS
  # LayersBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub highlightai-layers-${AWS::AccountId}
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true

  # LAMBDA LAYER: FFMPEG (Removed per user request)
  # FFmpegLayer:
  #   Type: AWS::Serverless::LayerVersion
  # ... (leaving commented out or removing)

  RawVideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub highlightai-raw-videos-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt UploadQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: videos/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldRawVideos
            Status: Enabled
            ExpirationInDays: 7
    # S3 BUCKET FOR EDITED VIDEO OUTPUTS
  EditedVideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub highlightai-edited-videos-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEditedVideos
            Status: Enabled
            ExpirationInDays: 7
  
  # SQS QUEUE FOR UPLOAD NOTIFICATIONS
  UploadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: highlightai-upload-queue
      VisibilityTimeout: 660
      MessageRetentionPeriod: 86400
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt UploadDLQ.Arn
        maxReceiveCount: 3

  UploadDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: highlightai-upload-dlq
      MessageRetentionPeriod: 1209600  # 14 days

  UploadQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UploadQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: !GetAtt UploadQueue.Arn
            Condition:
              StringLike:
                aws:SourceArn: !Sub arn:aws:s3:::highlightai-raw-videos-${AWS::AccountId}


  # DYNAMODB TABLE FOR VIDEO METADATA
  VideosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: highlightai-videos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: videoId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: videoId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserVideosIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES


  # COGNITO USER POOL
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: highlightai-users
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: highlightai-client
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30


  # API GATEWAY
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: highlightai-api
      StageName: dev
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowCredentials: false
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
            Identity:
              Header: Authorization
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"


  # LAMBDA: SIGNUP
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-signup
      CodeUri: lambdas/auth/
      Handler: signup.lambda_handler
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
              Resource: !GetAtt UserPool.Arn
      Events:
        SignupApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/signup
            Method: POST
            Auth:
              Authorizer: NONE

  # LAMBDA: SIGNIN
  SigninFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-signin
      CodeUri: lambdas/auth/
      Handler: signin.lambda_handler
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
              Resource: !GetAtt UserPool.Arn
      Events:
        SigninApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/signin
            Method: POST
            Auth:
              Authorizer: NONE

  # LAMBDA: PRESIGNED URL GENERATOR
  PresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-presigned-url
      CodeUri: lambdas/presigned-url/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          RAW_VIDEOS_BUCKET: !Ref RawVideosBucket
          VIDEOS_TABLE: !Ref VideosTable
          EDITED_VIDEOS_BUCKET: !Ref EditedVideosBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub ${RawVideosBucket.Arn}/videos/*
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt VideosTable.Arn
      Events:
        GetPresignedUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /upload/presigned-url
            Method: POST

    # IAM ROLE FOR VIDEO EDITOR LAMBDA
  
  VideoEditorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: VideoEditorPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            # S3 Access
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:HeadObject
                - s3:PutObject
                - s3:GetBucketLocation
                - s3:ListBucket
              Resource:
                - !Sub ${RawVideosBucket.Arn}
                - !Sub ${RawVideosBucket.Arn}/*
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub ${EditedVideosBucket.Arn}/*
            
            # Bedrock Access
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
             
            # DynamoDB Access
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt VideosTable.Arn
            
            # Transcribe Access
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
              Resource: !Sub arn:aws:transcribe:${AWS::Region}:${AWS::AccountId}:transcription-job/*
            
            # Rekognition Access
            - Effect: Allow
              Action:
                - rekognition:*
              Resource: '*'
            
            # MediaConvert Access
            - Effect: Allow
              Action:
                - mediaconvert:CreateJob
                - mediaconvert:DescribeEndpoints
                - mediaconvert:GetJob
              Resource: '*'
            
            # SQS Access (for reading messages)
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt UploadQueue.Arn
            
            # STS Access (for getting account ID)
            - Effect: Allow
              Action:
                - sts:GetCallerIdentity
              Resource: '*'
            
            # Pass MediaConvert role
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !GetAtt MediaConvertRole.Arn

  MediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MediaConvertS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub '${RawVideosBucket.Arn}/*'
                  - !Sub '${EditedVideosBucket.Arn}/*'


  # LAMBDA FUNCTION: VIDEO EDITOR
  VideoEditorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-video-editor
      CodeUri: lambdas/video-editor/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Timeout: 600  # 15 minutes (max for processing)
      MemorySize: 3008  # Max memory for performance
      # Layers:
        # - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:14
        # - arn:aws:lambda:us-east-1:145266761615:layer:ffmpeg:5
      Role: !GetAtt VideoEditorRole.Arn
      Environment:
        Variables:
          RAW_VIDEOS_BUCKET: !Ref RawVideosBucket
          EDITED_VIDEOS_BUCKET: !Ref EditedVideosBucket
          VIDEOS_TABLE: !Ref VideosTable
          REGION: !Ref AWS::Region
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt UploadQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 5


  ConsolidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-consolidation
      CodeUri: lambdas/consolidation/
      Handler: handler.consolidation_handler
      Runtime: python3.11
      Timeout: 600
      MemorySize: 1024
      Role: !GetAtt VideoEditorRole.Arn
      Environment:
        Variables:
          RAW_VIDEOS_BUCKET: !Ref RawVideosBucket
          EDITED_VIDEOS_BUCKET: !Ref EditedVideosBucket
          VIDEOS_TABLE: !Ref VideosTable
          REGION: !Ref AWS::Region
          MEDIA_CONVERT_ROLE_ARN: !GetAtt MediaConvertRole.Arn

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  RawVideosBucketName:
    Description: S3 Bucket for raw video uploads
    Value: !Ref RawVideosBucket
    Export:
      Name: !Sub ${AWS::StackName}-RawVideosBucket

  VideosTableName:
    Description: DynamoDB Table for video metadata
    Value: !Ref VideosTable
    Export:
      Name: !Sub ${AWS::StackName}-VideosTable

  UploadQueueUrl:
    Description: SQS Queue URL for upload notifications
    Value: !Ref UploadQueue
    Export:
      Name: !Sub ${AWS::StackName}-UploadQueueUrl
  EditedVideosBucketName:
    Description: S3 Bucket for edited video outputs
    Value: !Ref EditedVideosBucket
    Export:
      Name: !Sub ${AWS::StackName}-EditedVideosBucket
  
  VideoEditorFunctionArn:
    Description: ARN of video editor Lambda function
    Value: !GetAtt VideoEditorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VideoEditorArn

  VideoEditorRoleArn:
    Description: ARN of video editor IAM role
    Value: !GetAtt VideoEditorRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VideoEditorRole
  
  ConsolidationFunctionArn:
    Description: ARN of consolidation Lambda function
    Value: !GetAtt ConsolidationFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ConsolidationArn

  MediaConvertRoleArn:
    Description: ARN of MediaConvert IAM role
    Value: !GetAtt MediaConvertRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-MediaConvertRole

