AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HighlightAI - Authentication and Video Upload Module

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256

Resources:
  # S3 BUCKET FOR RAW VIDEO UPLOADS
  RawVideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub highlightai-raw-videos-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt UploadQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: videos/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldRawVideos
            Status: Enabled
            ExpirationInDays: 7

  # S3 BUCKET FOR EDITED VIDEO OUTPUTS (Debika's contribution)
  EditedVideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub highlightai-edited-videos-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEditedVideos
            Status: Enabled
            ExpirationInDays: 7

  # SQS QUEUE FOR UPLOAD NOTIFICATIONS
  UploadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: highlightai-upload-queue
      VisibilityTimeout: 660  # Increased for video processing
      MessageRetentionPeriod: 86400
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt UploadDLQ.Arn
        maxReceiveCount: 3

  UploadDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: highlightai-upload-dlq
      MessageRetentionPeriod: 1209600  # 14 days

  # SQS QUEUE FOR VIDEO EDITING/PROCESSING TEAM
  VideoProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: highlightai-video-processing-queue
      VisibilityTimeout: 900  # 15 minutes for video processing
      MessageRetentionPeriod: 345600  # 4 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt VideoProcessingDLQ.Arn
        maxReceiveCount: 3

  VideoProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: highlightai-video-processing-dlq
      MessageRetentionPeriod: 1209600  # 14 days

  UploadQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UploadQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: !GetAtt UploadQueue.Arn
            Condition:
              StringLike:
                aws:SourceArn: !Sub arn:aws:s3:::highlightai-raw-videos-${AWS::AccountId}


  # DYNAMODB TABLE FOR VIDEO METADATA
  VideosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: highlightai-videos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: videoId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: videoId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserVideosIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES


  # COGNITO USER POOL
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: highlightai-users
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: highlightai-client
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30


  # API GATEWAY
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: highlightai-api
      StageName: dev
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowCredentials: false
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false  # Fix CORS preflight OPTIONS requests
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
            Identity:
              Header: Authorization
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"


  # LAMBDA: SIGNUP
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-signup
      CodeUri: lambdas/auth/
      Handler: signup.lambda_handler
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
              Resource: !GetAtt UserPool.Arn
      Events:
        SignupApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/signup
            Method: POST
            Auth:
              Authorizer: NONE

  # LAMBDA: SIGNIN
  SigninFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-signin
      CodeUri: lambdas/auth/
      Handler: signin.lambda_handler
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
              Resource: !GetAtt UserPool.Arn
      Events:
        SigninApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/signin
            Method: POST
            Auth:
              Authorizer: NONE

  # LAMBDA: CONFIRM SIGNUP (OTP EMAIL VERIFICATION)
  ConfirmSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-confirm-signup
      CodeUri: lambdas/auth/
      Handler: confirm_signup.lambda_handler
      Environment:
        Variables:
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ConfirmSignUp
              Resource: !GetAtt UserPool.Arn
      Events:
        ConfirmSignupApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/confirm
            Method: POST
            Auth:
              Authorizer: NONE

  # LAMBDA: PRESIGNED URL GENERATOR
  PresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-presigned-url
      CodeUri: lambdas/presigned-url/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          RAW_VIDEOS_BUCKET: !Ref RawVideosBucket
          VIDEOS_TABLE: !Ref VideosTable
          EDITED_VIDEOS_BUCKET: !Ref EditedVideosBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub ${RawVideosBucket.Arn}/videos/*
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt VideosTable.Arn
      Events:
        GetPresignedUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /upload/presigned-url
            Method: POST

  # LAMBDA: UPLOAD COMPLETE HANDLER
  UploadCompleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-upload-complete
      CodeUri: lambdas/upload-complete/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          VIDEOS_TABLE: !Ref VideosTable
          VIDEO_PROCESSING_QUEUE_URL: !Ref VideoProcessingQueue
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !GetAtt VideosTable.Arn
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt UploadQueue.Arn
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt VideoProcessingQueue.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt UploadQueue.Arn
            BatchSize: 10

  # ========================================
  # DEBIKA'S AI VIDEO PROCESSING PIPELINE
  # ========================================

  # IAM ROLE FOR MEDIACONVERT
  MediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MediaConvertS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub '${RawVideosBucket.Arn}/*'
                  - !Sub '${EditedVideosBucket.Arn}/*'

  # IAM ROLE FOR VIDEO EDITOR LAMBDA
  VideoEditorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: VideoEditorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 Access
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                  - s3:PutObject
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !Sub ${RawVideosBucket.Arn}
                  - !Sub ${RawVideosBucket.Arn}/*
                  - !Sub ${EditedVideosBucket.Arn}
                  - !Sub ${EditedVideosBucket.Arn}/*
              
              # Bedrock Access (AI)
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
              
              # DynamoDB Access
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: !GetAtt VideosTable.Arn
              
              # Transcribe Access
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                Resource: '*'
              
              # Rekognition Access
              - Effect: Allow
                Action:
                  - rekognition:*
                Resource: '*'
              
              # MediaConvert Access
              - Effect: Allow
                Action:
                  - mediaconvert:CreateJob
                  - mediaconvert:DescribeEndpoints
                  - mediaconvert:GetJob
                Resource: '*'
              
              # SQS Access
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:SendMessage
                Resource:
                  - !GetAtt VideoProcessingQueue.Arn
              
              # STS Access
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
              
              # Pass MediaConvert role
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt MediaConvertRole.Arn

  # LAMBDA: VIDEO EDITOR (AI PROCESSING)
  VideoEditorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-video-editor
      CodeUri: lambdas/video-editor/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Timeout: 600  # 10 minutes for video processing
      MemorySize: 3008  # Max memory for performance
      Role: !GetAtt VideoEditorRole.Arn
      Environment:
        Variables:
          RAW_VIDEOS_BUCKET: !Ref RawVideosBucket
          EDITED_VIDEOS_BUCKET: !Ref EditedVideosBucket
          VIDEOS_TABLE: !Ref VideosTable
          REGION: !Ref AWS::Region
      Events:
        VideoProcessingEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt VideoProcessingQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 5

  # LAMBDA: CONSOLIDATION (COMBINES AI RESULTS)
  ConsolidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: highlightai-consolidation
      CodeUri: lambdas/consolidation/
      Handler: handler.consolidation_handler
      Runtime: python3.11
      Timeout: 600
      MemorySize: 1024
      Role: !GetAtt VideoEditorRole.Arn
      Environment:
        Variables:
          RAW_VIDEOS_BUCKET: !Ref RawVideosBucket
          EDITED_VIDEOS_BUCKET: !Ref EditedVideosBucket
          VIDEOS_TABLE: !Ref VideosTable
          REGION: !Ref AWS::Region
          MEDIA_CONVERT_ROLE_ARN: !GetAtt MediaConvertRole.Arn
      Events:
        TranscribeComplete:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.transcribe
              detail-type:
                - Transcribe Job State Change
              detail:
                TranscriptionJobStatus:
                  - COMPLETED

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  RawVideosBucketName:
    Description: S3 Bucket for raw video uploads
    Value: !Ref RawVideosBucket
    Export:
      Name: !Sub ${AWS::StackName}-RawVideosBucket

  VideosTableName:
    Description: DynamoDB Table for video metadata
    Value: !Ref VideosTable
    Export:
      Name: !Sub ${AWS::StackName}-VideosTable

  UploadQueueUrl:
    Description: SQS Queue URL for upload notifications
    Value: !Ref UploadQueue
    Export:
      Name: !Sub ${AWS::StackName}-UploadQueueUrl

  VideoProcessingQueueUrl:
    Description: SQS Queue URL for video processing/editing team
    Value: !Ref VideoProcessingQueue
    Export:
      Name: !Sub ${AWS::StackName}-VideoProcessingQueueUrl

  VideoProcessingQueueArn:
    Description: SQS Queue ARN for video processing/editing team
    Value: !GetAtt VideoProcessingQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VideoProcessingQueueArn

  EditedVideosBucketName:
    Description: S3 Bucket for edited video outputs (Debika's AI processing)
    Value: !Ref EditedVideosBucket
    Export:
      Name: !Sub ${AWS::StackName}-EditedVideosBucket

  VideoEditorFunctionArn:
    Description: ARN of video editor Lambda function
    Value: !GetAtt VideoEditorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-VideoEditorArn

  ConsolidationFunctionArn:
    Description: ARN of consolidation Lambda function
    Value: !GetAtt ConsolidationFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ConsolidationArn

  MediaConvertRoleArn:
    Description: ARN of MediaConvert IAM role
    Value: !GetAtt MediaConvertRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-MediaConvertRole
